import ExcelJS from 'exceljs'
import { Transaction, StatementMeta, detectTransactionType } from './gemini'

const ACCENT = 'FF00C896'
const HEADER_BG = 'FF1F2937'
const TITLE_BG = 'FF111827'
const ZEBRA_LIGHT = 'FFF8FAFB'
const DEBIT_TINT = 'FFFFF1F0'
const CREDIT_TINT = 'FFEFFFF6'
const DEBIT_TXT = 'FFC0392B'
const CREDIT_TXT = 'FF1E8449'

const formatPeriod = (m: StatementMeta): string => {
  if (m.period_from && m.period_to) return `${formatDate(m.period_from)} – ${formatDate(m.period_to)}`
  if (m.period_from) return `From ${formatDate(m.period_from)}`
  return ''
}

const formatDate = (iso: string): string => {
  try {
    const [y, m, d] = iso.split('-')
    return `${d}/${m}/${y}`
  } catch { return iso }
}

export async function generateExcel(
  transactions: Transaction[],
  meta: StatementMeta,
  options: { brandName?: string } = {}
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook()
  wb.creator = options.brandName || 'BankXL'
  wb.company = options.brandName || 'BankXL'
  wb.created = new Date()

  const ws = wb.addWorksheet('Transactions', {
    views: [{ state: 'frozen', ySplit: 4 }],
  })

  ws.columns = [
    { key: 'sno',     width: 6  },
    { key: 'date',    width: 14 },
    { key: 'desc',    width: 50 },
    { key: 'ref',     width: 18 },
    { key: 'type',    width: 12 },
    { key: 'debit',   width: 16 },
    { key: 'credit',  width: 16 },
    { key: 'balance', width: 16 },
  ]

  ws.mergeCells('A1:H1')
  const titleCell = ws.getCell('A1')
  titleCell.value = meta.bank_name ? `${meta.bank_name} — Statement of Account` : 'Bank Statement'
  titleCell.font = { name: 'Calibri', size: 14, bold: true, color: { argb: 'FFFFFFFF' } }
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TITLE_BG } }
  titleCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(1).height = 30

  ws.mergeCells('A2:H2')
  const subCell = ws.getCell('A2')
  const parts: string[] = []
  if (meta.account_holder) parts.push(meta.account_holder)
  if (meta.account_no) parts.push(`A/C: ${meta.account_no}`)
  if (meta.ifsc) parts.push(`IFSC: ${meta.ifsc}`)
  const period = formatPeriod(meta)
  if (period) parts.push(`Period: ${period}`)
  subCell.value = parts.join('  •  ') || `Generated by ${options.brandName || 'BankXL'}`
  subCell.font = { name: 'Calibri', size: 10, color: { argb: 'FFE5E7EB' } }
  subCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TITLE_BG } }
  subCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(2).height = 22

  ws.getRow(3).height = 6

  const headers = ['#', 'Date', 'Description / Narration', 'Ref / Cheque No', 'Type', 'Debit (Dr)', 'Credit (Cr)', 'Balance']
  const headerRow = ws.getRow(4)
  headers.forEach((h, i) => {
    const cell = headerRow.getCell(i + 1)
    cell.value = h
    cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_BG } }
    cell.alignment = { vertical: 'middle', horizontal: i >= 5 ? 'right' : i === 0 ? 'center' : 'left', indent: 1 }
    cell.border = { bottom: { style: 'medium', color: { argb: ACCENT } } }
  })
  headerRow.height = 24
  ws.autoFilter = { from: 'A4', to: 'H4' }

  let totalDebit = 0
  let totalCredit = 0

  transactions.forEach((tx, idx) => {
    const row = ws.addRow({
      sno: idx + 1,
      date: tx.date || '',
      desc: tx.description || '',
      ref: tx.ref_no || '',
      type: detectTransactionType(tx.description || ''),
      debit: tx.debit ?? '',
      credit: tx.credit ?? '',
      balance: tx.balance ?? '',
    })

    const isEven = idx % 2 === 0
    const rowBg = isEven ? ZEBRA_LIGHT : 'FFFFFFFF'

    row.eachCell((cell, colNum) => {
      cell.font = { name: 'Calibri', size: 10 }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowBg } }
      cell.border = { bottom: { style: 'hair', color: { argb: 'FFE5E7EB' } } }

      if (colNum >= 6 && colNum <= 8) {
        cell.numFmt = '#,##0.00;[Red]-#,##0.00'
        cell.alignment = { horizontal: 'right', indent: 1 }
      }
      if (colNum === 2 && tx.date) {
        cell.alignment = { horizontal: 'center' }
      }
      if (colNum === 1) cell.alignment = { horizontal: 'center' }
      if (colNum === 3) cell.alignment = { wrapText: true, vertical: 'top', indent: 1 }
      if (colNum === 4 || colNum === 5) cell.alignment = { vertical: 'middle', indent: 1 }
    })

    if (tx.debit) {
      const c = row.getCell(6)
      c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: DEBIT_TINT } }
      c.font = { name: 'Calibri', size: 10, color: { argb: DEBIT_TXT }, bold: true }
      totalDebit += tx.debit
    }
    if (tx.credit) {
      const c = row.getCell(7)
      c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: CREDIT_TINT } }
      c.font = { name: 'Calibri', size: 10, color: { argb: CREDIT_TXT }, bold: true }
      totalCredit += tx.credit
    }
    row.height = 20
  })

  ws.addRow([])
  const summaryRow = ws.addRow({
    sno: '',
    date: '',
    desc: `TOTAL — ${transactions.length} transactions`,
    ref: '',
    type: '',
    debit: totalDebit || '',
    credit: totalCredit || '',
    balance: '',
  })
  summaryRow.eachCell((cell, colNum) => {
    cell.font = { name: 'Calibri', size: 10, bold: true }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } }
    cell.border = { top: { style: 'medium', color: { argb: HEADER_BG } } }
    if (colNum >= 6 && colNum <= 8) {
      cell.numFmt = '#,##0.00'
      cell.alignment = { horizontal: 'right', indent: 1 }
    }
    if (colNum === 3) cell.alignment = { horizontal: 'right', indent: 1 }
  })
  summaryRow.getCell(6).font = { name: 'Calibri', size: 11, bold: true, color: { argb: DEBIT_TXT } }
  summaryRow.getCell(7).font = { name: 'Calibri', size: 11, bold: true, color: { argb: CREDIT_TXT } }
  summaryRow.height = 22

  // ─── Summary sheet ───────────────────────────────
  const ws2 = wb.addWorksheet('Summary')
  ws2.columns = [{ width: 32 }, { width: 26 }]

  const currency = meta.currency || 'INR'
  const numFmt = currency === 'INR' ? '"₹"#,##0.00' : `"${currency} "#,##0.00`

  const rows: [string, string | number][] = [
    [`${options.brandName || 'BankXL'} — Conversion Summary`, ''],
    ['', ''],
    ['Bank', meta.bank_name || '—'],
    ['Account holder', meta.account_holder || '—'],
    ['Account number', meta.account_no || '—'],
    ['IFSC', meta.ifsc || '—'],
    ['Period', formatPeriod(meta) || '—'],
    ['', ''],
    ['Opening balance', meta.opening_balance ?? '—'],
    ['Closing balance', meta.closing_balance ?? '—'],
    ['', ''],
    ['Total transactions', transactions.length],
    ['Total debits', totalDebit],
    ['Total credits', totalCredit],
    ['Net flow', totalCredit - totalDebit],
    ['', ''],
    ['Conversion date', new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })],
    ['Generated by', options.brandName || 'BankXL'],
  ]

  rows.forEach((row, i) => {
    const r = ws2.addRow(row)
    if (i === 0) {
      ws2.mergeCells(`A${i + 1}:B${i + 1}`)
      r.getCell(1).font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } }
      r.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: TITLE_BG } }
      r.getCell(1).alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
      r.height = 28
      return
    }
    r.getCell(1).font = { size: 11, color: { argb: 'FF6B7280' } }
    r.getCell(2).font = { size: 11, bold: true, color: { argb: 'FF111827' } }
    r.getCell(2).alignment = { horizontal: 'left' }
    if (typeof row[1] === 'number') {
      r.getCell(2).numFmt = numFmt
      if (i === 12) r.getCell(2).font = { size: 11, bold: true, color: { argb: DEBIT_TXT } }
      if (i === 13) r.getCell(2).font = { size: 11, bold: true, color: { argb: CREDIT_TXT } }
      if (i === 14) r.getCell(2).font = { size: 11, bold: true, color: { argb: ACCENT.replace('FF', 'FF') } }
    }
  })

  // ─── Categories sheet ────────────────────────────
  const ws3 = wb.addWorksheet('By Type')
  ws3.columns = [
    { header: 'Type', key: 'type', width: 18 },
    { header: 'Count', key: 'count', width: 10 },
    { header: 'Total Debit', key: 'debit', width: 16 },
    { header: 'Total Credit', key: 'credit', width: 16 },
  ]
  const headerRow3 = ws3.getRow(1)
  headerRow3.eachCell(cell => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_BG } }
    cell.alignment = { horizontal: 'left', indent: 1 }
    cell.border = { bottom: { style: 'medium', color: { argb: ACCENT } } }
  })
  headerRow3.height = 22

  const catMap = new Map<string, { count: number; debit: number; credit: number }>()
  for (const tx of transactions) {
    const type = detectTransactionType(tx.description || '')
    const cur = catMap.get(type) ?? { count: 0, debit: 0, credit: 0 }
    cur.count += 1
    if (tx.debit) cur.debit += tx.debit
    if (tx.credit) cur.credit += tx.credit
    catMap.set(type, cur)
  }
  const cats = [...catMap.entries()].sort((a, b) => b[1].count - a[1].count)
  cats.forEach(([type, v], i) => {
    const r = ws3.addRow({ type, count: v.count, debit: v.debit, credit: v.credit })
    r.eachCell((cell, col) => {
      cell.font = { size: 10 }
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: i % 2 ? 'FFFFFFFF' : ZEBRA_LIGHT } }
      if (col >= 3) { cell.numFmt = numFmt; cell.alignment = { horizontal: 'right', indent: 1 } }
    })
  })

  const buffer = await wb.xlsx.writeBuffer()
  return Buffer.from(buffer)
}
