export interface BankPageData {
  slug: string
  name: string
  shortName: string
  tagline: string
  metaDescription: string
  keywords: string[]
  color: string
  statementFeatures: string[]
  faqs: { q: string; a: string }[]
  steps: string[]
  formats: string[]
}

export const BANK_PAGES: Record<string, BankPageData> = {
  sbi: {
    slug: 'sbi',
    name: 'State Bank of India',
    shortName: 'SBI',
    tagline: 'Convert SBI bank statement PDF to Excel instantly',
    metaDescription: 'Convert your SBI (State Bank of India) bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with SBI e-statements, passbook PDFs, and password-protected files. Free to try.',
    keywords: ['sbi bank statement to excel', 'sbi statement pdf to excel', 'convert sbi statement', 'sbi e-statement to excel', 'sbi bank statement converter', 'state bank of india statement excel', 'sbi passbook to excel'],
    color: '#1a237e',
    statementFeatures: ['SBI e-Statements (internet banking)', 'SBI YONO app statements', 'SBI passbook PDFs', 'Password-protected SBI PDFs (after unlock)', 'Multi-page SBI statements (up to 500+ pages)', 'SBI salary account statements', 'SBI current account statements'],
    steps: ['Download your SBI statement from YONO or internet banking', 'Upload the PDF to BankXL', 'Get clean Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for import into any software', 'JSON for developers', 'Tally XML for direct Tally import'],
    faqs: [
      { q: 'Does BankXL work with password-protected SBI PDFs?', a: 'Yes, but you need to remove the password first using Adobe Acrobat or any free PDF unlocker. Once unlocked, BankXL handles the rest perfectly.' },
      { q: 'Which SBI statement formats does BankXL support?', a: 'All of them — SBI e-statements from internet banking, YONO app statements, branch-generated passbook PDFs, and mini-statement PDFs. Both current and savings accounts.' },
      { q: 'How accurate is the SBI statement conversion?', a: 'For digitally generated SBI PDFs, accuracy is 99.5%+. For scanned SBI passbook PDFs, it\'s 95%+ depending on scan quality. Always verify before final use.' },
      { q: 'Can I convert SBI statements for Tally import?', a: 'Yes. BankXL exports SBI transactions as Tally XML, which you can import directly into Tally Prime or Tally ERP 9 without any manual entry.' },
      { q: 'What if my SBI statement has 12 months of transactions?', a: 'No problem. BankXL handles statements of any length — even 500+ pages with thousands of transactions. The Pro plan (₹499/mo) gives you 800 pages per month.' },
    ],
  },

  hdfc: {
    slug: 'hdfc',
    name: 'HDFC Bank',
    shortName: 'HDFC',
    tagline: 'Convert HDFC Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your HDFC Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with HDFC NetBanking statements, HDFC mobile app statements and password-protected PDFs. Free to try.',
    keywords: ['hdfc bank statement to excel', 'hdfc statement pdf to excel', 'convert hdfc bank statement', 'hdfc netbanking statement excel', 'hdfc bank statement converter', 'hdfc statement to tally'],
    color: '#004c97',
    statementFeatures: ['HDFC NetBanking e-statements', 'HDFC MobileBanking app statements', 'HDFC salary account statements', 'HDFC current account statements', 'HDFC NRI account statements', 'Password-protected HDFC PDFs (after unlock)', 'Multi-year HDFC statements'],
    steps: ['Log into HDFC NetBanking or mobile app and download your statement', 'Upload the PDF to BankXL', 'Download your Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for import into any software', 'JSON for developers', 'Tally XML for direct Tally import'],
    faqs: [
      { q: 'Does BankXL support HDFC password-protected statements?', a: 'Yes — HDFC statements are often password-protected with your date of birth. Remove the password using any free PDF tool first, then upload to BankXL.' },
      { q: 'Can I convert HDFC NRI account statements?', a: 'Yes. BankXL works with all HDFC account types including NRE, NRO, and FCNR accounts.' },
      { q: 'How do I get my HDFC statement for conversion?', a: 'Log into HDFC NetBanking → Accounts → Select account → e-Statement → Download PDF. Or use the HDFC Mobile Banking app → Statements section.' },
      { q: 'Does it work with older HDFC statement formats?', a: 'Yes. BankXL handles all HDFC statement formats from 2015 onwards. If an older format doesn\'t work, email us and we\'ll fix it in 48 hours.' },
      { q: 'Can I import HDFC transactions directly into Tally?', a: 'Absolutely. Select the Tally XML format when downloading and import directly into Tally Prime or ERP 9 using the standard bank import feature.' },
    ],
  },

  icici: {
    slug: 'icici',
    name: 'ICICI Bank',
    shortName: 'ICICI',
    tagline: 'Convert ICICI Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your ICICI Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Supports ICICI iMobile, netbanking statements and password-protected PDFs. Free to try.',
    keywords: ['icici bank statement to excel', 'icici statement pdf to excel', 'icici bank statement converter', 'icici imobile statement excel', 'icici netbanking statement download excel', 'icici statement to tally'],
    color: '#f77f00',
    statementFeatures: ['ICICI iMobile app statements', 'ICICI Internet Banking e-statements', 'ICICI salary account statements', 'ICICI Pockets statements', 'ICICI NRI account statements', 'Password-protected ICICI PDFs', 'ICICI credit card statements'],
    steps: ['Download your ICICI statement from iMobile or Internet Banking', 'Upload the PDF to BankXL', 'Download your formatted Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for import into any software', 'JSON for developers', 'Tally XML for direct Tally import'],
    faqs: [
      { q: 'How do I download my ICICI Bank statement?', a: 'Log into ICICI Internet Banking → My Accounts → View Statement → Download PDF. Or use iMobile → Account Statement → Choose date range → Download.' },
      { q: 'Does BankXL work with ICICI password-protected PDFs?', a: 'Yes — ICICI often protects statements with your date of birth (DDMMYYYY format). Remove the password first, then upload to BankXL for instant conversion.' },
      { q: 'Can I convert ICICI credit card statements to Excel?', a: 'Yes. BankXL extracts all transactions from ICICI credit card statements too, including transaction descriptions, dates, amounts, and balances.' },
      { q: 'Does BankXL handle ICICI NRI account statements?', a: 'Yes. All ICICI account types are supported — savings, current, NRE, NRO, and FCNR accounts.' },
      { q: 'Can I batch convert multiple ICICI statements at once?', a: 'Yes — the Firm plan includes bulk ZIP upload, so you can upload 50 statements at once and download all converted files in one ZIP.' },
    ],
  },

  axis: {
    slug: 'axis',
    name: 'Axis Bank',
    shortName: 'Axis',
    tagline: 'Convert Axis Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Axis Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Axis Bank NetBanking, mobile app statements and password-protected PDFs. Free to try.',
    keywords: ['axis bank statement to excel', 'axis bank statement pdf to excel', 'axis bank statement converter', 'convert axis bank statement', 'axis bank netbanking statement excel', 'axis statement to tally'],
    color: '#800000',
    statementFeatures: ['Axis Bank NetBanking e-statements', 'Axis Bank mobile app statements', 'Axis Bank salary account statements', 'Axis Bank current account statements', 'Password-protected Axis PDFs', 'Multi-page Axis statements'],
    steps: ['Log into Axis Bank NetBanking or mobile app and download your statement', 'Upload the PDF to BankXL', 'Get your Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for import into any software', 'JSON for developers', 'Tally XML for direct Tally import'],
    faqs: [
      { q: 'How do I download my Axis Bank statement?', a: 'Log into Axis Bank Internet Banking → Accounts → Select account → Account Statement → Download as PDF. Or use the Axis Mobile app → Statements section.' },
      { q: 'Does BankXL support Axis Bank password-protected statements?', a: 'Yes — after removing the password. Axis Bank often uses your date of birth or account number as the password. Use any free PDF tool to unlock first.' },
      { q: 'Can I convert Axis Bank statements for Tally?', a: 'Yes. BankXL exports Axis Bank transactions as Tally XML for direct import into Tally Prime or ERP 9.' },
      { q: 'Does BankXL work with Axis Bank current account statements?', a: 'Absolutely. Both savings and current account statements from Axis Bank are fully supported.' },
      { q: 'What if my Axis statement has handwritten entries?', a: 'BankXL\'s AI uses OCR to read scanned and handwritten entries, though accuracy may vary. For best results, use digital e-statements from internet banking.' },
    ],
  },

  kotak: {
    slug: 'kotak',
    name: 'Kotak Mahindra Bank',
    shortName: 'Kotak',
    tagline: 'Convert Kotak Mahindra Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Kotak Mahindra Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Kotak 811, NetBanking, mobile app statements and password-protected PDFs. Free to try.',
    keywords: ['kotak bank statement to excel', 'kotak mahindra statement pdf to excel', 'kotak 811 statement converter', 'kotak netbanking statement excel', 'kotak bank statement converter', 'kotak statement to tally'],
    color: '#ee3124',
    statementFeatures: ['Kotak NetBanking e-statements', 'Kotak 811 digital bank statements', 'Kotak Mobile Banking app statements', 'Kotak salary account statements', 'Kotak current account statements', 'Password-protected Kotak PDFs'],
    steps: ['Download your Kotak statement from NetBanking or the Kotak app', 'Upload the PDF to BankXL', 'Get clean Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for import into any software', 'JSON for developers', 'Tally XML for direct Tally import'],
    faqs: [
      { q: 'How do I download my Kotak Bank statement?', a: 'Log into Kotak NetBanking → My Accounts → Select account → Account Statement → Download PDF. Or in the Kotak app → Accounts → Statement → Download.' },
      { q: 'Does BankXL support Kotak 811 statements?', a: 'Yes. Kotak 811 is a fully digital bank — its statements are clean PDFs that BankXL converts with 99%+ accuracy.' },
      { q: 'Can I convert Kotak Bank statements for Tally import?', a: 'Yes. Export your converted statement as Tally XML and import directly into Tally Prime or ERP 9.' },
      { q: 'Does BankXL handle Kotak password-protected PDFs?', a: 'Yes — after removing the password. Kotak often uses your date of birth (DD/MM/YYYY) or a custom password. Unlock first, then convert.' },
      { q: 'Can BankXL handle Kotak statements with foreign currency transactions?', a: 'Yes. BankXL extracts all transaction data including foreign currency amounts and exchange rates as they appear in the statement.' },
    ],
  },

  pnb: {
    slug: 'pnb',
    name: 'Punjab National Bank',
    shortName: 'PNB',
    tagline: 'Convert PNB bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Punjab National Bank (PNB) statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with PNB ONE app, internet banking statements. Free to try.',
    keywords: ['pnb bank statement to excel', 'punjab national bank statement pdf excel', 'pnb statement converter', 'pnb one statement excel', 'convert pnb bank statement'],
    color: '#ff6600',
    statementFeatures: ['PNB ONE app statements', 'PNB Internet Banking e-statements', 'PNB savings account statements', 'PNB current account statements', 'PNB Jan Dhan account statements'],
    steps: ['Download your PNB statement from PNB ONE app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I download my PNB statement?', a: 'Log into PNB ONE app or internet banking → Accounts → Account Statement → Select date range → Download PDF.' },
      { q: 'Does BankXL work with old PNB statement formats?', a: 'Yes. BankXL handles PNB statements from 2010 onwards in both old and new formats.' },
      { q: 'Can I convert PNB statements to Tally XML?', a: 'Yes. Select Tally XML format at download and import directly into Tally Prime or ERP 9.' },
    ],
  },

  canara: {
    slug: 'canara',
    name: 'Canara Bank',
    shortName: 'Canara',
    tagline: 'Convert Canara Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Canara Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Canara ai1 app and internet banking statements. Free to try.',
    keywords: ['canara bank statement to excel', 'canara bank pdf to excel', 'canara statement converter', 'canara ai1 statement excel', 'convert canara bank statement'],
    color: '#007a33',
    statementFeatures: ['Canara ai1 app statements', 'Canara Internet Banking statements', 'Canara savings and current account statements', 'Multi-page Canara statements'],
    steps: ['Download your Canara statement from the app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel with all transactions in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I get my Canara Bank statement?', a: 'Use the Canara ai1 app (Accounts → Statements → Download) or Canara Internet Banking → Account Statement → Download PDF.' },
      { q: 'Does BankXL convert Canara Bank statements accurately?', a: 'Yes. Canara Bank statements have a consistent format that BankXL reads with 99%+ accuracy.' },
    ],
  },

  'bank-of-baroda': {
    slug: 'bank-of-baroda',
    name: 'Bank of Baroda',
    shortName: 'BoB',
    tagline: 'Convert Bank of Baroda statement PDF to Excel instantly',
    metaDescription: 'Convert your Bank of Baroda (BoB) statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Bob World app and internet banking. Free to try.',
    keywords: ['bank of baroda statement to excel', 'bob bank statement pdf excel', 'bank of baroda statement converter', 'bob world statement excel', 'convert bank of baroda statement'],
    color: '#f26522',
    statementFeatures: ['Bob World app statements', 'Bank of Baroda internet banking statements', 'BoB savings and current account statements', 'BoB NRI account statements'],
    steps: ['Download your BoB statement from Bob World app or internet banking', 'Upload the PDF to BankXL', 'Download your Excel in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I download my Bank of Baroda statement?', a: 'Use the Bob World app → Accounts → Statement → Download, or BoB internet banking → My Accounts → Account Statement → Download PDF.' },
      { q: 'Can I use the converted BoB statement with Tally?', a: 'Yes. Download the Tally XML format and import directly into Tally Prime or ERP 9.' },
    ],
  },

  'idfc-first': {
    slug: 'idfc-first',
    name: 'IDFC First Bank',
    shortName: 'IDFC First',
    tagline: 'Convert IDFC First Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your IDFC First Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with IDFC First Bank mobile app and internet banking. Free to try.',
    keywords: ['idfc first bank statement to excel', 'idfc first statement pdf excel', 'idfc first bank statement converter', 'idfc bank statement excel', 'convert idfc statement'],
    color: '#f26522',
    statementFeatures: ['IDFC First Bank mobile app statements', 'IDFC First Internet Banking statements', 'IDFC First salary account statements', 'IDFC First FIRST Classic/Wealth statements'],
    steps: ['Download your IDFC First statement from the app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I get my IDFC First Bank statement?', a: 'Open the IDFC First Bank app → Accounts → Account Statement → Download PDF, or use internet banking → Accounts → e-Statement → Download.' },
      { q: 'Does BankXL handle IDFC First Bank\'s statement format accurately?', a: 'Yes. IDFC First Bank statements are clean digital PDFs that BankXL reads with 99%+ accuracy.' },
    ],
  },

  indusind: {
    slug: 'indusind',
    name: 'IndusInd Bank',
    shortName: 'IndusInd',
    tagline: 'Convert IndusInd Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your IndusInd Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with IndusMobile app and internet banking. Free to try.',
    keywords: ['indusind bank statement to excel', 'indusind statement pdf excel', 'indusmobile statement converter', 'indusind bank statement excel', 'convert indusind statement'],
    color: '#004a97',
    statementFeatures: ['IndusMobile app statements', 'IndusInd Internet Banking statements', 'IndusInd savings and current account statements', 'IndusInd NRI statements'],
    steps: ['Download your IndusInd statement from IndusMobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I download my IndusInd Bank statement?', a: 'Use the IndusMobile app → Accounts → Account Statement → Download, or internet banking → Accounts → e-Statement → Download PDF.' },
      { q: 'Can I convert IndusInd statements for Tally?', a: 'Yes. Export as Tally XML and import directly into Tally Prime or ERP 9.' },
    ],
  },

  'yes-bank': {
    slug: 'yes-bank',
    name: 'Yes Bank',
    shortName: 'Yes Bank',
    tagline: 'Convert Yes Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Yes Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with YES PAY, YES Mobile and internet banking statements. Free to try.',
    keywords: ['yes bank statement to excel', 'yes bank pdf to excel', 'yes bank statement converter', 'yes mobile statement excel', 'convert yes bank statement'],
    color: '#00439c',
    statementFeatures: ['YES Mobile app statements', 'Yes Bank Internet Banking statements', 'Yes Bank savings account statements', 'Yes Bank current account statements'],
    steps: ['Download your Yes Bank statement from YES Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I get my Yes Bank statement?', a: 'Use YES Mobile → Accounts → Statements → Download PDF, or Yes Bank internet banking → Accounts → Account Statement → Download.' },
      { q: 'Does BankXL work with Yes Bank password-protected PDFs?', a: 'Yes — after removing the password. Unlock the PDF first using any free tool, then upload to BankXL.' },
    ],
  },

  federal: {
    slug: 'federal',
    name: 'Federal Bank',
    shortName: 'Federal',
    tagline: 'Convert Federal Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Federal Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with FedMobile, FedNet and internet banking statements. Free to try.',
    keywords: ['federal bank statement to excel', 'federal bank pdf to excel', 'fedmobile statement excel', 'federal bank statement converter', 'convert federal bank statement'],
    color: '#1a3a6b',
    statementFeatures: ['FedMobile app statements', 'FedNet internet banking statements', 'Federal Bank savings account statements', 'Federal Bank NRI statements'],
    steps: ['Download your Federal Bank statement from FedMobile or FedNet', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx)', 'CSV', 'JSON', 'Tally XML'],
    faqs: [
      { q: 'How do I get my Federal Bank statement?', a: 'Use FedMobile app → Accounts → Statement → Download, or FedNet → Accounts → Account Statement → Download PDF.' },
      { q: 'Can I use BankXL for Federal Bank NRI statements?', a: 'Yes. Federal Bank NRE and NRO account statements are fully supported.' },
    ],
  },

  'bank-of-india': {
    slug: 'bank-of-india',
    name: 'Bank of India',
    shortName: 'BOI',
    tagline: 'Convert Bank of India statement PDF to Excel instantly',
    metaDescription: 'Convert your Bank of India (BOI) statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with BOI Mobile, StarConnect internet banking and passbook PDFs. Free to try.',
    keywords: ['bank of india statement to excel', 'boi statement pdf to excel', 'convert bank of india statement', 'starconnect statement excel', 'boi passbook to excel'],
    color: '#f78d1e',
    statementFeatures: ['BOI Mobile app statements', 'StarConnect internet banking statements', 'BOI passbook PDFs', 'BOI current & savings account statements', 'Password-protected BOI PDFs (after unlock)'],
    steps: ['Download your BOI statement from StarConnect or BOI Mobile', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my BOI statement?', a: 'Log into StarConnect internet banking → Accounts → Statement → select period → Download PDF. Or use the BOI Mobile app → Statement → Email/Download.' },
      { q: 'Does BankXL work with password-protected BOI statements?', a: 'Yes, after removing the password. Open the PDF in Adobe Reader → File → Print → Save as PDF to create an unlocked copy.' },
      { q: 'Is BankXL good for BOI Tally import?', a: 'Yes — export your BOI statement as Tally XML and use Ctrl+I in Tally Prime / ERP 9 to import receipts and payments as vouchers.' },
    ],
  },

  'union-bank': {
    slug: 'union-bank',
    name: 'Union Bank of India',
    shortName: 'Union Bank',
    tagline: 'Convert Union Bank of India statement PDF to Excel instantly',
    metaDescription: 'Convert your Union Bank of India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Union Bank internet banking and passbook PDFs. Free to try.',
    keywords: ['union bank statement to excel', 'union bank of india pdf to excel', 'convert union bank statement', 'union bank internet banking statement excel'],
    color: '#c8102e',
    statementFeatures: ['Union Bank Vyom app statements', 'Union Bank internet banking statements', 'Union Bank passbook PDFs', 'Union Bank NRI statements', 'Post-merger e-Andhra & e-Corporation account formats'],
    steps: ['Download your Union Bank statement from internet banking or Vyom app', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Union Bank statement?', a: 'Log into Union Bank internet banking → Accounts → Statement → select period → Download PDF. Or use the Vyom app → Statement → Download.' },
      { q: 'Does BankXL support post-merger Union Bank formats?', a: 'Yes. Statements from ex-Andhra Bank and ex-Corporation Bank accounts (now under Union Bank of India after the 2020 merger) work fine.' },
      { q: 'Can I convert Union Bank statements for Tally import?', a: 'Yes — export as Tally XML and use Ctrl+I in Tally Prime / ERP 9. Receipts and payments land as proper vouchers.' },
    ],
  },

  'indian-bank': {
    slug: 'indian-bank',
    name: 'Indian Bank',
    shortName: 'Indian Bank',
    tagline: 'Convert Indian Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Indian Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with IndOASIS app, internet banking and passbook PDFs. Free to try.',
    keywords: ['indian bank statement to excel', 'indian bank pdf to excel', 'convert indian bank statement', 'indoasis statement excel', 'indian bank passbook to excel'],
    color: '#0b3b8f',
    statementFeatures: ['IndOASIS mobile app statements', 'Indian Bank internet banking statements', 'Indian Bank passbook PDFs', 'Indian Bank NRI account statements', 'Post-merger ex-Allahabad Bank account formats'],
    steps: ['Download your Indian Bank statement from IndOASIS or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Indian Bank statement?', a: 'Use IndOASIS mobile app → Accounts → Statement → Download PDF. Or Indian Bank internet banking → Accounts → e-Statement → select period.' },
      { q: 'Does BankXL work with ex-Allahabad Bank statements?', a: 'Yes. After the 2020 merger, ex-Allahabad Bank accounts are now under Indian Bank — their statement format is fully supported.' },
      { q: 'Can I use this for Indian Bank Tally import?', a: 'Yes — Tally XML export lets you import all transactions as proper vouchers into Tally Prime or ERP 9.' },
    ],
  },

  rbl: {
    slug: 'rbl',
    name: 'RBL Bank',
    shortName: 'RBL',
    tagline: 'Convert RBL Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your RBL Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with RBL MyBank app, internet banking and credit card statements. Free to try.',
    keywords: ['rbl bank statement to excel', 'rbl pdf to excel', 'convert rbl bank statement', 'rbl mybank statement excel', 'rbl credit card statement to excel'],
    color: '#c8102e',
    statementFeatures: ['RBL MyBank app statements', 'RBL Bank internet banking statements', 'RBL credit card statements', 'RBL savings & current account statements', 'RBL business banking statements'],
    steps: ['Download your RBL statement from MyBank app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my RBL Bank statement?', a: 'Use the RBL MyBank app → Accounts → e-Statement → Download PDF. Or RBL internet banking → Accounts → Statement → select period → Download.' },
      { q: 'Does BankXL work with RBL credit card statements?', a: 'Yes. RBL credit card PDFs convert cleanly with all transaction details preserved.' },
      { q: 'Can I convert RBL statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'au-sfb': {
    slug: 'au-sfb',
    name: 'AU Small Finance Bank',
    shortName: 'AU SFB',
    tagline: 'Convert AU Small Finance Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your AU Small Finance Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with AU 0101 app, AU Wingman internet banking and account PDFs. Free to try.',
    keywords: ['au bank statement to excel', 'au small finance bank pdf to excel', 'au sfb statement converter', 'au 0101 statement excel', 'convert au bank statement'],
    color: '#8b1c62',
    statementFeatures: ['AU 0101 mobile app statements', 'AU Wingman internet banking statements', 'AU SFB savings & current account statements', 'AU SFB business banking statements', 'AU credit card statements'],
    steps: ['Download your AU SFB statement from AU 0101 or Wingman', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my AU SFB statement?', a: 'Use AU 0101 mobile app → Accounts → Statement → Download. Or AU Wingman internet banking → Accounts → Account Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with AU credit card statements?', a: 'Yes. AU Bank credit card PDFs are supported alongside their savings, current and business account statements.' },
      { q: 'Can I convert AU SFB statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  bandhan: {
    slug: 'bandhan',
    name: 'Bandhan Bank',
    shortName: 'Bandhan',
    tagline: 'Convert Bandhan Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Bandhan Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Bandhan mobile banking and internet banking statements. Free to try.',
    keywords: ['bandhan bank statement to excel', 'bandhan bank pdf to excel', 'convert bandhan bank statement', 'bandhan bank statement converter'],
    color: '#a91d4c',
    statementFeatures: ['Bandhan mobile banking statements', 'Bandhan internet banking statements', 'Bandhan savings & current account statements', 'Bandhan microfinance loan statements'],
    steps: ['Download your Bandhan Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Bandhan Bank statement?', a: 'Use the Bandhan mobile banking app → Accounts → e-Statement → Download PDF. Or internet banking → Accounts → Statement → select period → Download.' },
      { q: 'Does BankXL work with all Bandhan account types?', a: 'Yes — savings, current, and microfinance loan account statements are all supported.' },
      { q: 'Can I convert Bandhan statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'south-indian-bank': {
    slug: 'south-indian-bank',
    name: 'South Indian Bank',
    shortName: 'SIB',
    tagline: 'Convert South Indian Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your South Indian Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with SIB Mirror+ app and internet banking statements. Free to try.',
    keywords: ['south indian bank statement to excel', 'sib pdf to excel', 'convert south indian bank statement', 'sib mirror statement excel'],
    color: '#004b87',
    statementFeatures: ['SIB Mirror+ mobile app statements', 'South Indian Bank internet banking statements', 'SIB savings & current account statements', 'SIB NRI account statements'],
    steps: ['Download your South Indian Bank statement from Mirror+ app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my South Indian Bank statement?', a: 'Use SIB Mirror+ app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with SIB NRI account statements?', a: 'Yes. NRI, NRE and NRO account statements are supported alongside regular savings and current accounts.' },
      { q: 'Can I convert South Indian Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  'karnataka-bank': {
    slug: 'karnataka-bank',
    name: 'Karnataka Bank',
    shortName: 'KBL',
    tagline: 'Convert Karnataka Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Karnataka Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with KBL Mobile+ and internet banking statements. Free to try.',
    keywords: ['karnataka bank statement to excel', 'kbl pdf to excel', 'convert karnataka bank statement', 'kbl mobile plus statement excel'],
    color: '#00447c',
    statementFeatures: ['KBL Mobile+ app statements', 'Karnataka Bank internet banking statements', 'KBL savings & current account statements', 'KBL business banking statements'],
    steps: ['Download your Karnataka Bank statement from KBL Mobile+ or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Karnataka Bank statement?', a: 'Use KBL Mobile+ app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with KBL business account statements?', a: 'Yes. Business current account and cash credit statements are supported alongside savings accounts.' },
      { q: 'Can I convert Karnataka Bank statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'karur-vysya-bank': {
    slug: 'karur-vysya-bank',
    name: 'Karur Vysya Bank',
    shortName: 'KVB',
    tagline: 'Convert Karur Vysya Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Karur Vysya Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with KVB mobile banking and internet banking statements. Free to try.',
    keywords: ['karur vysya bank statement to excel', 'kvb pdf to excel', 'convert karur vysya bank statement', 'kvb statement converter'],
    color: '#7a1f2b',
    statementFeatures: ['KVB mobile banking statements', 'Karur Vysya Bank internet banking statements', 'KVB savings & current account statements', 'KVB MSME loan account statements'],
    steps: ['Download your Karur Vysya Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Karur Vysya Bank statement?', a: 'Use the KVB mobile banking app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with KVB MSME loan statements?', a: 'Yes. MSME and business loan account statements are supported alongside savings and current accounts.' },
      { q: 'Can I convert Karur Vysya Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  'city-union-bank': {
    slug: 'city-union-bank',
    name: 'City Union Bank',
    shortName: 'CUB',
    tagline: 'Convert City Union Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your City Union Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with CUB mobile banking and internet banking statements. Free to try.',
    keywords: ['city union bank statement to excel', 'cub pdf to excel', 'convert city union bank statement', 'cub statement converter'],
    color: '#0f5ba3',
    statementFeatures: ['CUB mobile banking statements', 'City Union Bank internet banking statements', 'CUB savings & current account statements', 'CUB MSME loan account statements'],
    steps: ['Download your City Union Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my City Union Bank statement?', a: 'Use the CUB mobile banking app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with CUB MSME statements?', a: 'Yes. MSME and business loan account statements are supported alongside savings and current accounts.' },
      { q: 'Can I convert City Union Bank statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  dcb: {
    slug: 'dcb',
    name: 'DCB Bank',
    shortName: 'DCB',
    tagline: 'Convert DCB Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your DCB Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with DCB mobile banking and internet banking statements. Free to try.',
    keywords: ['dcb bank statement to excel', 'dcb pdf to excel', 'convert dcb bank statement', 'dcb bank statement converter'],
    color: '#00539b',
    statementFeatures: ['DCB mobile banking statements', 'DCB internet banking statements', 'DCB savings & current account statements', 'DCB business banking statements'],
    steps: ['Download your DCB Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my DCB Bank statement?', a: 'Use the DCB mobile banking app → Accounts → e-Statement → Download PDF. Or internet banking → Accounts → Statement → select period → Download.' },
      { q: 'Does BankXL work with DCB business account statements?', a: 'Yes — business current account statements are supported alongside savings accounts.' },
      { q: 'Can I convert DCB statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  dhanlaxmi: {
    slug: 'dhanlaxmi',
    name: 'Dhanlaxmi Bank',
    shortName: 'Dhanlaxmi',
    tagline: 'Convert Dhanlaxmi Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Dhanlaxmi Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Dhanlaxmi mobile and internet banking statements. Free to try.',
    keywords: ['dhanlaxmi bank statement to excel', 'dhanlaxmi pdf to excel', 'convert dhanlaxmi bank statement'],
    color: '#8b1e3f',
    statementFeatures: ['Dhanlaxmi mobile banking statements', 'Dhanlaxmi internet banking statements', 'Dhanlaxmi savings & current account statements'],
    steps: ['Download your Dhanlaxmi Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Dhanlaxmi Bank statement?', a: 'Use the Dhanlaxmi mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL support all Dhanlaxmi account types?', a: 'Yes — savings, current, and NRI account statements are all supported.' },
      { q: 'Can I convert Dhanlaxmi statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  tmb: {
    slug: 'tmb',
    name: 'Tamilnad Mercantile Bank',
    shortName: 'TMB',
    tagline: 'Convert Tamilnad Mercantile Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Tamilnad Mercantile Bank (TMB) statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with TMB mobile and internet banking statements. Free to try.',
    keywords: ['tamilnad mercantile bank statement to excel', 'tmb pdf to excel', 'convert tmb bank statement'],
    color: '#004b8d',
    statementFeatures: ['TMB mobile banking statements', 'TMB internet banking statements', 'TMB savings & current account statements', 'TMB business banking statements'],
    steps: ['Download your TMB statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my TMB statement?', a: 'Use the TMB mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with TMB business account statements?', a: 'Yes — business current and cash credit account statements are supported alongside savings accounts.' },
      { q: 'Can I convert TMB statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  csb: {
    slug: 'csb',
    name: 'CSB Bank',
    shortName: 'CSB',
    tagline: 'Convert CSB Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your CSB Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with CSB mobile and internet banking statements. Free to try.',
    keywords: ['csb bank statement to excel', 'csb pdf to excel', 'convert csb bank statement'],
    color: '#003c71',
    statementFeatures: ['CSB mobile banking statements', 'CSB internet banking statements', 'CSB savings & current account statements'],
    steps: ['Download your CSB Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my CSB Bank statement?', a: 'Use the CSB mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with CSB NRI account statements?', a: 'Yes — NRI, NRE and NRO account statements are supported alongside regular savings and current accounts.' },
      { q: 'Can I convert CSB statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  nainital: {
    slug: 'nainital',
    name: 'Nainital Bank',
    shortName: 'Nainital',
    tagline: 'Convert Nainital Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Nainital Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Nainital Bank internet banking statements. Free to try.',
    keywords: ['nainital bank statement to excel', 'nainital bank pdf to excel', 'convert nainital bank statement'],
    color: '#0f5c3f',
    statementFeatures: ['Nainital Bank internet banking statements', 'Nainital Bank savings & current account statements'],
    steps: ['Download your Nainital Bank statement from internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Nainital Bank statement?', a: 'Use Nainital Bank internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Can I convert Nainital Bank statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'central-bank': {
    slug: 'central-bank',
    name: 'Central Bank of India',
    shortName: 'Central Bank',
    tagline: 'Convert Central Bank of India statement PDF to Excel instantly',
    metaDescription: 'Convert your Central Bank of India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Cent Mobile app and internet banking statements. Free to try.',
    keywords: ['central bank of india statement to excel', 'central bank pdf to excel', 'cent mobile statement excel', 'convert central bank of india statement'],
    color: '#004990',
    statementFeatures: ['Cent Mobile app statements', 'Central Bank internet banking statements', 'Central Bank savings & current account statements', 'Central Bank pension account statements'],
    steps: ['Download your Central Bank of India statement from Cent Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Central Bank of India statement?', a: 'Use the Cent Mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with pension account statements?', a: 'Yes — pension and savings account statements are supported alongside current accounts.' },
      { q: 'Can I convert Central Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  iob: {
    slug: 'iob',
    name: 'Indian Overseas Bank',
    shortName: 'IOB',
    tagline: 'Convert Indian Overseas Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Indian Overseas Bank (IOB) statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with IOB Mobile and internet banking statements. Free to try.',
    keywords: ['indian overseas bank statement to excel', 'iob pdf to excel', 'iob mobile statement excel', 'convert iob bank statement'],
    color: '#c8102e',
    statementFeatures: ['IOB Mobile app statements', 'IOB internet banking statements', 'IOB savings & current account statements', 'IOB NRI account statements'],
    steps: ['Download your IOB statement from IOB Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my IOB statement?', a: 'Use the IOB Mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with IOB NRI account statements?', a: 'Yes — NRI, NRE and NRO account statements are supported alongside regular savings and current accounts.' },
      { q: 'Can I convert IOB statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  uco: {
    slug: 'uco',
    name: 'UCO Bank',
    shortName: 'UCO',
    tagline: 'Convert UCO Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your UCO Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with UCO mBanking Plus and internet banking statements. Free to try.',
    keywords: ['uco bank statement to excel', 'uco pdf to excel', 'uco mbanking statement excel', 'convert uco bank statement'],
    color: '#0033a0',
    statementFeatures: ['UCO mBanking Plus app statements', 'UCO internet banking statements', 'UCO savings & current account statements'],
    steps: ['Download your UCO Bank statement from mBanking Plus or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my UCO Bank statement?', a: 'Use the UCO mBanking Plus app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with UCO business account statements?', a: 'Yes — business current account statements are supported alongside savings accounts.' },
      { q: 'Can I convert UCO Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  'bank-of-maharashtra': {
    slug: 'bank-of-maharashtra',
    name: 'Bank of Maharashtra',
    shortName: 'BoM',
    tagline: 'Convert Bank of Maharashtra statement PDF to Excel instantly',
    metaDescription: 'Convert your Bank of Maharashtra statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Maha Mobile app and internet banking statements. Free to try.',
    keywords: ['bank of maharashtra statement to excel', 'bom pdf to excel', 'maha mobile statement excel', 'convert bank of maharashtra statement'],
    color: '#00539f',
    statementFeatures: ['Maha Mobile app statements', 'Bank of Maharashtra internet banking statements', 'BoM savings & current account statements'],
    steps: ['Download your Bank of Maharashtra statement from Maha Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Bank of Maharashtra statement?', a: 'Use the Maha Mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with BoM business account statements?', a: 'Yes — business current account statements are supported alongside savings accounts.' },
      { q: 'Can I convert Bank of Maharashtra statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'punjab-sind-bank': {
    slug: 'punjab-sind-bank',
    name: 'Punjab & Sind Bank',
    shortName: 'PSB',
    tagline: 'Convert Punjab & Sind Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Punjab & Sind Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with PSB mobile and internet banking statements. Free to try.',
    keywords: ['punjab and sind bank statement to excel', 'psb pdf to excel', 'convert punjab sind bank statement'],
    color: '#8b1a1a',
    statementFeatures: ['PSB mobile banking statements', 'Punjab & Sind Bank internet banking statements', 'PSB savings & current account statements'],
    steps: ['Download your Punjab & Sind Bank statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Punjab & Sind Bank statement?', a: 'Use the PSB mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Can I convert Punjab & Sind Bank statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  hsbc: {
    slug: 'hsbc',
    name: 'HSBC India',
    shortName: 'HSBC',
    tagline: 'Convert HSBC India statement PDF to Excel instantly',
    metaDescription: 'Convert your HSBC India bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with HSBC India mobile and internet banking statements. Free to try.',
    keywords: ['hsbc india statement to excel', 'hsbc pdf to excel', 'convert hsbc bank statement india', 'hsbc statement converter'],
    color: '#db0011',
    statementFeatures: ['HSBC India mobile banking statements', 'HSBC internet banking statements', 'HSBC savings & current account statements', 'HSBC NRI account statements', 'HSBC Premier statements'],
    steps: ['Download your HSBC India statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my HSBC India statement?', a: 'Use the HSBC India mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with HSBC Premier and NRI account statements?', a: 'Yes — Premier, NRI, NRE and NRO account statements are all supported.' },
      { q: 'Can I convert HSBC statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'standard-chartered': {
    slug: 'standard-chartered',
    name: 'Standard Chartered India',
    shortName: 'StanChart',
    tagline: 'Convert Standard Chartered India statement PDF to Excel instantly',
    metaDescription: 'Convert your Standard Chartered India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with SC Mobile and internet banking statements. Free to try.',
    keywords: ['standard chartered india statement to excel', 'standard chartered pdf to excel', 'sc mobile statement excel', 'convert standard chartered statement'],
    color: '#0473ea',
    statementFeatures: ['SC Mobile app statements', 'Standard Chartered internet banking statements', 'Priority Banking statements', 'NRI account statements'],
    steps: ['Download your Standard Chartered statement from SC Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Standard Chartered statement?', a: 'Use the SC Mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Priority Banking and NRI statements?', a: 'Yes — Priority Banking, NRI, NRE and NRO account statements are all supported.' },
      { q: 'Can I convert Standard Chartered statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  citibank: {
    slug: 'citibank',
    name: 'Citibank India',
    shortName: 'Citi',
    tagline: 'Convert Citibank India statement PDF to Excel instantly',
    metaDescription: 'Convert your Citibank India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Citi Mobile and internet banking statements. Free to try.',
    keywords: ['citibank india statement to excel', 'citi pdf to excel', 'citi mobile statement excel', 'convert citibank statement india'],
    color: '#003b70',
    statementFeatures: ['Citi Mobile app statements', 'Citibank internet banking statements', 'Citigold account statements', 'Citi credit card statements', 'NRI account statements'],
    steps: ['Download your Citibank statement from Citi Mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Citibank statement?', a: 'Use the Citi Mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Citi credit card statements?', a: 'Yes — Citi credit card PDFs convert cleanly alongside savings, current and Citigold account statements.' },
      { q: 'Can I convert Citibank statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'deutsche-bank': {
    slug: 'deutsche-bank',
    name: 'Deutsche Bank India',
    shortName: 'Deutsche Bank',
    tagline: 'Convert Deutsche Bank India statement PDF to Excel instantly',
    metaDescription: 'Convert your Deutsche Bank India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Deutsche Bank internet banking statements. Free to try.',
    keywords: ['deutsche bank india statement to excel', 'deutsche bank pdf to excel', 'convert deutsche bank statement india'],
    color: '#0018a8',
    statementFeatures: ['Deutsche Bank internet banking statements', 'Deutsche Bank savings & current account statements', 'NRI account statements'],
    steps: ['Download your Deutsche Bank India statement from internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Deutsche Bank India statement?', a: 'Use Deutsche Bank internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Deutsche Bank NRI account statements?', a: 'Yes — NRI, NRE and NRO account statements are supported.' },
      { q: 'Can I convert Deutsche Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  dbs: {
    slug: 'dbs',
    name: 'DBS Bank India',
    shortName: 'DBS',
    tagline: 'Convert DBS Bank India statement PDF to Excel instantly',
    metaDescription: 'Convert your DBS Bank India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with digibank by DBS and internet banking statements. Free to try.',
    keywords: ['dbs bank india statement to excel', 'dbs pdf to excel', 'digibank statement excel', 'convert dbs bank statement india'],
    color: '#ed1b34',
    statementFeatures: ['digibank by DBS app statements', 'DBS internet banking statements', 'DBS savings & current account statements', 'DBS business banking statements'],
    steps: ['Download your DBS Bank India statement from digibank app or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my DBS Bank India statement?', a: 'Use the digibank by DBS app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with DBS business account statements?', a: 'Yes — business current account statements are supported alongside savings accounts.' },
      { q: 'Can I convert DBS statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  barclays: {
    slug: 'barclays',
    name: 'Barclays India',
    shortName: 'Barclays',
    tagline: 'Convert Barclays India statement PDF to Excel instantly',
    metaDescription: 'Convert your Barclays India statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Barclays India internet banking statements. Free to try.',
    keywords: ['barclays india statement to excel', 'barclays pdf to excel', 'convert barclays bank statement india'],
    color: '#00aeef',
    statementFeatures: ['Barclays India internet banking statements', 'Barclays savings & current account statements'],
    steps: ['Download your Barclays India statement from internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Barclays India statement?', a: 'Use Barclays India internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Can I convert Barclays statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  paytm: {
    slug: 'paytm',
    name: 'Paytm Payments Bank',
    shortName: 'Paytm',
    tagline: 'Convert Paytm Payments Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Paytm Payments Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Paytm app wallet and bank account statements. Free to try.',
    keywords: ['paytm payments bank statement to excel', 'paytm pdf to excel', 'paytm bank statement converter', 'convert paytm statement'],
    color: '#00baf2',
    statementFeatures: ['Paytm app wallet statements', 'Paytm Payments Bank savings account statements', 'Paytm business account statements'],
    steps: ['Download your Paytm Payments Bank statement from the Paytm app', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Paytm Payments Bank statement?', a: 'Open the Paytm app → Paytm Payments Bank → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Paytm business account statements?', a: 'Yes — Paytm business account statements convert alongside regular savings account statements.' },
      { q: 'Can I convert Paytm statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  'airtel-payments-bank': {
    slug: 'airtel-payments-bank',
    name: 'Airtel Payments Bank',
    shortName: 'Airtel Bank',
    tagline: 'Convert Airtel Payments Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Airtel Payments Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Airtel Thanks app statements. Free to try.',
    keywords: ['airtel payments bank statement to excel', 'airtel bank pdf to excel', 'convert airtel payments bank statement'],
    color: '#e40000',
    statementFeatures: ['Airtel Thanks app statements', 'Airtel Payments Bank savings account statements'],
    steps: ['Download your Airtel Payments Bank statement from the Airtel Thanks app', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Airtel Payments Bank statement?', a: 'Open the Airtel Thanks app → Bank → Statement → select period → Download PDF.' },
      { q: 'Can I convert Airtel Payments Bank statements for Tally import?', a: 'Yes — export as Tally XML for direct Ctrl+I import into Tally Prime or ERP 9.' },
    ],
  },

  'fino-payments-bank': {
    slug: 'fino-payments-bank',
    name: 'Fino Payments Bank',
    shortName: 'Fino',
    tagline: 'Convert Fino Payments Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Fino Payments Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Fino app and merchant account statements. Free to try.',
    keywords: ['fino payments bank statement to excel', 'fino pdf to excel', 'convert fino payments bank statement'],
    color: '#f7941d',
    statementFeatures: ['Fino app statements', 'Fino Payments Bank savings account statements', 'Fino merchant account statements'],
    steps: ['Download your Fino Payments Bank statement from the Fino app', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Fino Payments Bank statement?', a: 'Open the Fino app → Account → Statement → select period → Download PDF.' },
      { q: 'Can I convert Fino statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  ujjivan: {
    slug: 'ujjivan',
    name: 'Ujjivan Small Finance Bank',
    shortName: 'Ujjivan SFB',
    tagline: 'Convert Ujjivan Small Finance Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Ujjivan Small Finance Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Ujjivan mobile and internet banking statements. Free to try.',
    keywords: ['ujjivan bank statement to excel', 'ujjivan sfb pdf to excel', 'convert ujjivan bank statement'],
    color: '#f47b20',
    statementFeatures: ['Ujjivan mobile banking statements', 'Ujjivan internet banking statements', 'Ujjivan savings & current account statements', 'Ujjivan microfinance loan statements'],
    steps: ['Download your Ujjivan SFB statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Ujjivan SFB statement?', a: 'Use the Ujjivan mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Ujjivan microfinance loan statements?', a: 'Yes — microfinance and business loan account statements are supported alongside savings and current accounts.' },
      { q: 'Can I convert Ujjivan statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  equitas: {
    slug: 'equitas',
    name: 'Equitas Small Finance Bank',
    shortName: 'Equitas SFB',
    tagline: 'Convert Equitas Small Finance Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Equitas Small Finance Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Equitas mobile and internet banking statements. Free to try.',
    keywords: ['equitas bank statement to excel', 'equitas sfb pdf to excel', 'convert equitas bank statement'],
    color: '#00a651',
    statementFeatures: ['Equitas mobile banking statements', 'Equitas internet banking statements', 'Equitas savings & current account statements', 'Equitas microfinance loan statements'],
    steps: ['Download your Equitas SFB statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Equitas SFB statement?', a: 'Use the Equitas mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Equitas microfinance loan statements?', a: 'Yes — microfinance and business loan account statements are supported alongside savings and current accounts.' },
      { q: 'Can I convert Equitas statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },

  jana: {
    slug: 'jana',
    name: 'Jana Small Finance Bank',
    shortName: 'Jana SFB',
    tagline: 'Convert Jana Small Finance Bank statement PDF to Excel instantly',
    metaDescription: 'Convert your Jana Small Finance Bank statement PDF to Excel, CSV or Tally XML in 15 seconds. Works with Jana mobile and internet banking statements. Free to try.',
    keywords: ['jana bank statement to excel', 'jana sfb pdf to excel', 'convert jana bank statement'],
    color: '#7a1e3d',
    statementFeatures: ['Jana mobile banking statements', 'Jana internet banking statements', 'Jana savings & current account statements', 'Jana microfinance loan statements'],
    steps: ['Download your Jana SFB statement from mobile or internet banking', 'Upload the PDF to BankXL', 'Get your Excel in 15 seconds'],
    formats: ['Excel (.xlsx) with color-coded debits/credits', 'CSV for accounting software', 'JSON for developers', 'Tally XML for direct import'],
    faqs: [
      { q: 'How do I download my Jana SFB statement?', a: 'Use the Jana mobile app → Accounts → e-Statement → Download. Or internet banking → Accounts → Statement → select period → Download PDF.' },
      { q: 'Does BankXL work with Jana microfinance loan statements?', a: 'Yes — microfinance and business loan account statements are supported alongside savings and current accounts.' },
      { q: 'Can I convert Jana statements for Tally import?', a: 'Yes — Tally XML export lets you import transactions as vouchers directly into Tally Prime or ERP 9.' },
    ],
  },
}

export const ALL_BANK_SLUGS = Object.keys(BANK_PAGES)
