/**
 * app/for/[persona]/data.ts — content for industry/persona landing pages.
 *
 * Priority-order (per SEO strategy §5, month 1-3 P0):
 *   /for/chartered-accountants — "bank statement converter for ca" (210 mo, KD 10)
 *
 * More personas (ca-firms, auditors, tax-consultants, bookkeepers,
 * loan-consultants, finance-teams) can be added by appending entries below.
 */

export interface PersonaPageData {
  slug: string
  persona: string             // "Chartered Accountants"
  personaShort: string        // "CAs"
  primaryKeyword: string
  metaTitle: string
  metaDescription: string
  keywords: string[]
  hero: {
    kicker: string
    h1Prefix: string
    h1Highlight: string
    h1Suffix: string
    subhead: string
  }
  painPoints: string[]        // "Stop doing X" bullets
  workflows: { title: string; before: string; after: string }[]
  features: { title: string; desc: string; big?: boolean }[]
  testimonial: { text: string; name: string; role: string }
  faqs: { q: string; a: string }[]
  proofPoints: string[]        // trust-signal chips shown near hero CTA
}

export const PERSONA_PAGES: Record<string, PersonaPageData> = {

  // ─── Chartered Accountants ────────────────────────────────────────────────
  'chartered-accountants': {
    slug: 'chartered-accountants',
    persona: 'Chartered Accountants',
    personaShort: 'CAs',
    primaryKeyword: 'bank statement converter for ca',
    metaTitle: 'Bank Statement Converter for Chartered Accountants',
    metaDescription: 'Purpose-built bank statement PDF-to-Excel converter for Indian CAs. Tally XML export, bulk upload, 500+ banks. Trusted by 1,200+ chartered accountants. Free 50 pages/month.',
    keywords: [
      'bank statement converter for ca', 'bank statement tool for chartered accountants',
      'ca software for bank statements', 'bank statement pdf to excel for accountants',
      'tally bank statement converter for ca', 'bulk bank statement converter for ca',
      'ca firm bank statement software', 'bank statement processing for chartered accountants',
    ],
    hero: {
      kicker: 'BUILT FOR CHARTERED ACCOUNTANTS',
      h1Prefix: 'The bank-statement workflow',
      h1Highlight: '1,200+ Indian CAs',
      h1Suffix: 'trust every day.',
      subhead: 'Stop typing SBI, HDFC and ICICI statements into Excel by hand. BankXL converts any Indian bank PDF into clean Excel or Tally-import-ready XML in 15 seconds — with the accuracy and audit trail your practice needs.',
    },
    proofPoints: ['1,200+ CAs onboard', 'Trusted for FY audits', '500+ banks supported'],
    painPoints: [
      'Stop retyping SBI passbooks row by row for GST reconciliation',
      'Skip the manual voucher entry for every client\'s HDFC statement in Tally',
      'End the "which page did I miss?" checks on 50-page ICICI e-statements',
      'Get juniors off bank data-entry and back on real work',
    ],
    workflows: [
      { title: 'Monthly reconciliation',
        before: 'Download client PDFs → open Excel → type 200-500 rows → fix formatting → reconcile.',
        after: 'Upload PDFs to BankXL → download formatted Excel with color-coded debits/credits + summary sheet → reconcile.' },
      { title: 'Tally import at year-end',
        before: 'Manually create receipt/payment vouchers for every transaction on every bank statement.',
        after: 'Upload → export as Tally XML → import into Tally with Ctrl+I. Vouchers land automatically.' },
      { title: 'GST audit for a new client',
        before: 'Get 12 months × multiple banks × hundreds of rows. Team spends 2-3 days on data entry alone.',
        after: 'Bulk upload all statements → convert in parallel → analyse categorised data on day one.' },
      { title: 'Loan-scoring / DSCR analysis',
        before: 'Type debit-credit patterns into Excel by hand, hope you didn\'t miss a big transaction.',
        after: 'Convert to CSV or JSON. Every UPI, NEFT, IMPS captured with reference numbers intact.' },
    ],
    features: [
      { title: 'Tally XML export (Prime & ERP 9)', big: true,
        desc: 'One-click export produces a Tally-import-ready XML with proper receipt / payment vouchers, correct date format, and reference numbers preserved as narrations. No plugin, no TDL, no third-party add-on — uses Tally\'s built-in Ctrl+I import.' },
      { title: 'Bulk conversion for firms', big: true,
        desc: 'Upload up to 50 statements in one batch. Each runs in parallel, results land in your dashboard as they finish. Perfect for month-end, quarterly audit season, or a new client onboarding.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Scanned PDFs too',
        desc: 'Old passbook scans, faxed statements, image-based PDFs — AI reads them all at near-perfect accuracy.' },
      { title: 'Team seats',
        desc: 'Firm plan: 5 team seats included. Shared usage, shared history, one subscription.' },
      { title: 'Client-safe by design',
        desc: 'Files processed in memory, deleted after conversion. Zero data retention. Nothing shared with third parties.' },
    ],
    testimonial: {
      text: "I used to spend two hours retyping every client's SBI and HDFC statements. BankXL does it in twenty seconds. Honestly the best money I spend each month.",
      name: 'Rajesh Agarwal',
      role: 'Chartered Accountant, Delhi',
    },
    faqs: [
      { q: 'How is BankXL different from generic PDF-to-Excel tools like iLovePDF or Smallpdf?',
        a: 'Generic tools extract every visible block of text — you get raw tables you then have to re-format for hours. BankXL is purpose-built for bank statements: it detects the bank, splits debit/credit into separate columns, preserves running balance, drops junk rows like "BROUGHT FORWARD" and "OPENING BALANCE", and can export to Tally XML directly. What takes 45 minutes of Excel cleanup with generic tools takes 15 seconds with BankXL.' },
      { q: 'Which Indian banks are supported?',
        a: 'All the ones you work with: SBI, HDFC, ICICI, Axis, Kotak, PNB, Bank of Baroda, Canara, IDFC First, IndusInd, Yes Bank, Federal, RBL, IDBI, AU SFB, and 90+ others. Also international banks (Chase, BoA, Wells Fargo, HSBC, DBS) if you handle NRI or export clients.' },
      { q: 'Can I use it for Tally import?',
        a: 'Yes — this is why most CAs subscribe. BankXL exports Tally XML that imports cleanly into Tally Prime or Tally ERP 9 via the built-in Ctrl+I import. Receipts and payments are created as proper vouchers with reference numbers preserved as narrations. See our /convert/bank-statement-to-tally page for details.' },
      { q: 'Is there a Firm plan for CA offices?',
        a: 'Yes. The Firm plan is ₹4,999/month for 8,000 pages, 5 team seats, bulk upload (up to 50 files at once), and white-label Excel with your firm name in the summary sheet. Perfect for medium firms with articles and partners sharing the workload.' },
      { q: 'What about data privacy? My clients trust me with their bank data.',
        a: 'Files are processed in memory and deleted immediately after conversion. Nothing is written to disk long-term. We don\'t train AI on your data or share it with anyone. If you need extra assurance, we can provide a DPA — email support@banlxlai.com.' },
      { q: 'What if my client\'s statement is password-protected?',
        a: 'Remove the password once using Adobe Reader or any PDF viewer (File → Print → Save as PDF works), then upload. BankXL processes the unlocked file. This is the standard flow — Reserve Bank of India rules mean bank statements often come password-locked, so every CA we work with is used to this step.' },
      { q: 'Can I try it before committing?',
        a: 'Yes. Free plan is 50 pages every month, no credit card. Convert 2-3 typical client statements to see the output quality for yourself before deciding on a paid plan.' },
      { q: 'Is BankXL an ICAI-approved tool?',
        a: 'BankXL is a productivity tool — it converts PDFs to data. ICAI doesn\'t certify converters. What matters for your practice is accuracy (99.5%+ on digital PDFs, 95%+ on scans) and data safety (zero retention). Always review the extracted Excel before finalising audit workpapers, as you would with any input.' },
    ],
  },

  // ─── Auditors ──────────────────────────────────────────────────────────────
  'auditors': {
    slug: 'auditors',
    persona: 'Auditors',
    personaShort: 'Auditors',
    primaryKeyword: 'bank statement tool for auditors',
    metaTitle: 'Bank Statement Converter for Auditors',
    metaDescription: 'Verify and cross-check client bank statements fast. Convert PDFs to structured Excel for audit trails, sampling, and reconciliation. Trusted by audit teams. Free 50 pages/month.',
    keywords: [
      'bank statement tool for auditors', 'bank statement for auditors', 'audit bank statement software',
      'bank statement verification tool', 'bank statement pdf to excel for audit',
      'financial audit bank statement converter', 'audit trail bank statement tool',
    ],
    hero: {
      kicker: 'BUILT FOR AUDITORS',
      h1Prefix: 'Cross-check bank statements',
      h1Highlight: 'without retyping a single row',
      h1Suffix: '.',
      subhead: 'Statutory and internal audits mean verifying hundreds of transactions against ledgers. BankXL converts client bank PDFs into structured Excel in 15 seconds so your team spends time on verification, not data entry.',
    },
    proofPoints: ['Used across statutory & internal audits', '500+ banks supported', 'Zero data retention'],
    painPoints: [
      'Stop manually transcribing bank statements before you can even start sampling',
      'End version-control chaos from multiple team members re-typing the same PDF',
      'Skip re-checking every row for typos introduced during manual entry',
      'Stop losing a day of audit fieldwork time to formatting spreadsheets',
    ],
    workflows: [
      { title: 'Bank confirmation cross-check',
        before: 'Type out the client\'s bank statement by hand to compare against the bank confirmation letter, row by row.',
        after: 'Upload the statement PDF → get a structured Excel → paste into your working paper and compare against the confirmation in minutes.' },
      { title: 'Transaction sampling',
        before: 'Scroll through a PDF, manually noting down transactions that meet your sampling criteria.',
        after: 'Convert to Excel, filter/sort by amount or date, and pull your sample directly with formulas.' },
      { title: 'Multi-entity audit',
        before: 'A client with 5 subsidiaries means 5 different bank formats to manually key in separately.',
        after: 'Bulk upload all 5 statements — each is normalized into the same column structure for consolidated review.' },
      { title: 'Related-party transaction review',
        before: 'Manually scan hundreds of rows looking for transfers to related entities.',
        after: 'Export to Excel or JSON and use formulas or scripts to flag transactions above a threshold or to known counterparties.' },
    ],
    features: [
      { title: 'Structured, audit-ready Excel output', big: true,
        desc: 'Every statement converts into a consistent column layout — date, narration, debit, credit, running balance, reference number — regardless of which bank issued the original PDF. Makes cross-client comparison and workpaper referencing straightforward.' },
      { title: 'Bulk conversion for multi-entity audits', big: true,
        desc: 'Upload up to 50 statements in one batch — ideal for group audits with several subsidiaries or a client with multiple bank accounts.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Scanned & old statements',
        desc: 'Historical passbook scans and image-based PDFs for multi-year audits are handled at near-perfect accuracy.' },
      { title: 'JSON export for scripted checks',
        desc: 'Export as JSON to run custom Python/Excel-VBA scripts for anomaly detection or related-party flagging.' },
      { title: 'Client-safe by design',
        desc: 'Files processed in memory, deleted after conversion. Zero data retention — important for client confidentiality during fieldwork.' },
    ],
    testimonial: {
      text: 'During a group audit with four subsidiaries, we had all the bank data structured and cross-checkable in under an hour instead of a full day of manual entry.',
      name: 'Priya Nair',
      role: 'Audit Manager, Bengaluru',
    },
    faqs: [
      { q: 'Is BankXL suitable for statutory audits?',
        a: 'Yes. BankXL converts bank statement PDFs into structured data for your working papers — it doesn\'t replace professional judgment or audit procedures. Always verify the extracted data against source documents as part of your standard audit trail.' },
      { q: 'Can I convert statements from multiple subsidiaries at once?',
        a: 'Yes — the Firm plan supports bulk upload of up to 50 statements per batch, each normalized into the same column structure for easy consolidation.' },
      { q: 'Does BankXL retain client bank data?',
        a: 'No. Files are processed in memory and deleted immediately after conversion. Nothing is stored long-term or used to train AI models.' },
      { q: 'Can BankXL detect fraud or anomalies?',
        a: 'BankXL converts and structures data — it doesn\'t perform fraud detection itself. But structured Excel/JSON output makes it easy to apply your own analytical procedures, formulas, or scripts for anomaly detection.' },
      { q: 'What if a client statement is old or scanned?',
        a: 'BankXL handles scanned and image-based PDFs, including older passbook-style statements often needed for multi-year audits, at 95%+ accuracy.' },
      { q: 'Can I try it before using it on a live engagement?',
        a: 'Yes — the free plan includes 50 pages every month, no credit card required, so you can test output quality on a sample statement first.' },
    ],
  },

  // ─── Tax Consultants ────────────────────────────────────────────────────────
  'tax-consultants': {
    slug: 'tax-consultants',
    persona: 'Tax Consultants',
    personaShort: 'Tax Consultants',
    primaryKeyword: 'bank statement converter for tax consultants',
    metaTitle: 'Bank Statement Converter for Tax Consultants',
    metaDescription: 'Prepare client bank statements for ITR filing and GST returns in seconds, not hours. Convert PDFs to Excel or CSV. Built for Indian tax consultants. Free 50 pages/month.',
    keywords: [
      'bank statement converter for tax consultants', 'tax consultant bank statement tool',
      'bank statement for itr filing', 'bank statement pdf to excel for tax filing',
      'gst bank statement converter', 'income tax bank statement analysis tool',
    ],
    hero: {
      kicker: 'BUILT FOR TAX CONSULTANTS',
      h1Prefix: 'ITR and GST season',
      h1Highlight: 'without the data-entry backlog',
      h1Suffix: '.',
      subhead: 'Every client hands you a stack of bank statement PDFs during filing season. BankXL converts them into clean Excel in 15 seconds, so you can reconcile income, categorize transactions, and file faster — even during peak season crunch.',
    },
    proofPoints: ['Built for ITR & GST season', '500+ banks supported', 'Free 50 pages/month'],
    painPoints: [
      'Stop manually re-typing client statements every filing season',
      'End the scramble to reconcile bank credits against declared income by hand',
      'Skip formatting raw PDF text dumps from generic PDF tools before you can even start',
      'Stop asking clients to "just send the Excel" — most only have the PDF',
    ],
    workflows: [
      { title: 'ITR income reconciliation',
        before: 'Manually scan bank statements for salary credits, interest income, and other receipts to cross-check against Form 26AS/AIS.',
        after: 'Convert to Excel, filter credits by narration keywords, and reconcile against 26AS in minutes.' },
      { title: 'GST return preparation',
        before: 'Type out every business transaction from the bank statement to build the turnover working.',
        after: 'Upload → get categorized Excel with debit/credit columns → build your GST turnover working directly from the data.' },
      { title: 'Multiple clients during peak season',
        before: 'Each of 30+ clients sends a PDF; team manually enters each one, falling behind during the March/July crunch.',
        after: 'Bulk upload all client statements in one batch — conversions run in parallel, freeing the team to focus on filing.' },
      { title: 'Cash flow verification for scrutiny cases',
        before: 'Painstakingly retype 12 months of transactions to respond to a tax notice.',
        after: 'Convert the full year\'s statements to Excel in one pass and prepare your response with structured data.' },
    ],
    features: [
      { title: 'Fast turnaround during peak filing season', big: true,
        desc: 'Convert a full year of statements in 15 seconds per file — critical when ITR and GST deadlines mean dozens of clients need processing in the same week.' },
      { title: 'Bulk conversion for multiple clients', big: true,
        desc: 'Upload up to 50 statements in one batch during peak season. Each processes in parallel so your whole client backlog moves at once.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'CSV export for tax software',
        desc: 'Export as CSV to import directly into ITR filing utilities or GST reconciliation tools that accept spreadsheet uploads.' },
      { title: 'Clean debit/credit separation',
        desc: 'Every transaction is split into debit and credit columns automatically — makes income and expense categorization for filing much faster.' },
      { title: 'Client-safe by design',
        desc: 'Files processed in memory, deleted after conversion. No data retention, no sharing with third parties.' },
    ],
    testimonial: {
      text: 'During July filing season I had 40+ clients each sending bank PDFs. BankXL let my team process all of them in an afternoon instead of a week.',
      name: 'Sanjay Mehta',
      role: 'Tax Consultant, Pune',
    },
    faqs: [
      { q: 'Can BankXL help reconcile income for ITR filing?',
        a: 'Yes. Converting the statement to Excel gives you a structured view of credits and debits that you can filter and cross-check against Form 26AS/AIS for income reconciliation.' },
      { q: 'Is it useful for GST turnover working?',
        a: 'Yes — many tax consultants use BankXL to quickly build the bank-side turnover working for GST returns, especially for clients without proper bookkeeping.' },
      { q: 'Can I process many clients at once during peak season?',
        a: 'Yes. The Firm plan supports bulk upload of up to 50 statements per batch, which is especially useful during March and July filing crunches.' },
      { q: 'Does it work for old or scanned bank statements needed for scrutiny cases?',
        a: 'Yes. Scanned and image-based PDFs, including multi-year historical statements, are supported at 95%+ accuracy.' },
      { q: 'Is client data safe?',
        a: 'Yes. Files are processed in memory and deleted immediately after conversion — no long-term storage, no AI training on your data.' },
      { q: 'Can I try it before filing season?',
        a: 'Yes — 50 free pages every month, no credit card. Test it on a client statement to confirm accuracy before the season starts.' },
    ],
  },

  // ─── Loan Consultants ───────────────────────────────────────────────────────
  'loan-consultants': {
    slug: 'loan-consultants',
    persona: 'Loan Consultants',
    personaShort: 'Loan Consultants',
    primaryKeyword: 'loan processing bank statement analysis',
    metaTitle: 'Bank Statement Converter for Loan Consultants',
    metaDescription: 'Analyze applicant bank statements for loan eligibility in seconds, not hours. Convert PDFs to Excel with every UPI, NEFT and salary credit captured. Free 50 pages/month.',
    keywords: [
      'loan processing bank statement analysis', 'bank statement analysis for loan approval',
      'bank statement converter for loan consultants', 'loan eligibility bank statement tool',
      'dscr analysis bank statement converter', 'bank statement pdf to excel for loans',
    ],
    hero: {
      kicker: 'BUILT FOR LOAN CONSULTANTS & DSAs',
      h1Prefix: 'Assess loan eligibility',
      h1Highlight: 'without typing a single transaction',
      h1Suffix: '.',
      subhead: 'Every loan application means reading months of bank statements to check income stability, existing EMIs, and average balance. BankXL converts applicant PDFs into structured Excel in 15 seconds so you can score eligibility instead of typing numbers.',
    },
    proofPoints: ['Built for DSAs & loan consultants', '500+ banks supported', 'Free 50 pages/month'],
    painPoints: [
      'Stop manually scanning 6-12 months of statements for salary credits and bounced EMIs',
      'End the guesswork around average monthly balance — calculate it precisely from real data',
      'Skip retyping applicant statements before you can even start your eligibility sheet',
      'Stop losing loan turnaround time to formatting spreadsheets instead of underwriting',
    ],
    workflows: [
      { title: 'Income stability check',
        before: 'Scroll through 6-12 months of PDFs manually looking for consistent salary credits.',
        after: 'Convert to Excel, filter credits by narration keywords like "SALARY" or employer name, and see a clean monthly trend.' },
      { title: 'Existing EMI / obligation check',
        before: 'Manually spot recurring debit amounts that look like existing loan EMIs across months.',
        after: 'Sort debits by amount and recurrence in Excel — repeating same-amount debits stand out immediately.' },
      { title: 'Average balance & bounce check',
        before: 'Type out daily/monthly closing balances by hand to compute average balance and spot cheque bounces.',
        after: 'Running balance column comes pre-extracted — build the average balance and bounce-flag formulas directly.' },
      { title: 'Multi-applicant / co-applicant cases',
        before: 'Each applicant\'s statement gets typed up separately, slowing down joint-loan processing.',
        after: 'Bulk upload all applicant statements together — each converts in parallel with consistent columns for side-by-side comparison.' },
    ],
    features: [
      { title: 'Every transaction captured with reference numbers', big: true,
        desc: 'UPI, NEFT, IMPS, RTGS and cheque transactions all convert with their reference numbers intact — critical for verifying salary credits and flagging unusual large transfers during underwriting.' },
      { title: 'Bulk conversion for multi-applicant cases', big: true,
        desc: 'Upload statements for the primary applicant and co-applicants together — up to 50 files per batch on the Firm plan, each normalized into the same column layout.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Running balance preserved',
        desc: 'The balance-after-transaction column carries through to Excel — the basis for average monthly balance and minimum balance calculations.' },
      { title: 'CSV/JSON for scoring models',
        desc: 'Export as CSV or JSON to feed directly into an in-house eligibility scoring spreadsheet or model.' },
      { title: 'Applicant-safe by design',
        desc: 'Files processed in memory, deleted after conversion. Zero data retention for sensitive financial documents.' },
    ],
    testimonial: {
      text: 'I process 15-20 loan files a week. What used to be a full day of manually reading statements is now an hour of reviewing clean Excel sheets.',
      name: 'Vikram Chawla',
      role: 'Loan Consultant (DSA), Mumbai',
    },
    faqs: [
      { q: 'Can BankXL calculate loan eligibility for me?',
        a: 'No — BankXL converts and structures the bank statement data. You still apply your own eligibility criteria and judgment. What it removes is the hours of manual data entry needed before you can even start that analysis.' },
      { q: 'Does it capture UPI and NEFT reference numbers?',
        a: 'Yes. Every transaction — UPI, NEFT, IMPS, RTGS, cheque — converts with its reference number and narration intact, which is often needed to verify the source of large credits.' },
      { q: 'Can I process co-applicant statements together?',
        a: 'Yes. The Firm plan supports bulk upload of up to 50 statements in one batch, useful for joint-loan or co-applicant cases where you need to compare multiple statements side by side.' },
      { q: 'Does BankXL work with statements from smaller/regional banks?',
        a: 'Yes — 500+ banks are supported including regional and small finance banks. If an applicant\'s bank isn\'t recognized, email a sample to support@banlxlai.com and we\'ll add it, usually within 24 hours.' },
      { q: 'Is applicant data kept private?',
        a: 'Yes. Files are processed in memory and deleted immediately after conversion. No long-term storage, and data is never used to train AI models.' },
      { q: 'Can I try it on a real applicant statement first?',
        a: 'Yes — the free plan includes 50 pages every month, no credit card, so you can check output quality before relying on it for live loan files.' },
    ],
  },

  // ─── Bookkeepers ────────────────────────────────────────────────────────────
  'bookkeepers': {
    slug: 'bookkeepers',
    persona: 'Bookkeepers',
    personaShort: 'Bookkeepers',
    primaryKeyword: 'bank statement tools for bookkeepers',
    metaTitle: 'Bank Statement Converter for Bookkeepers',
    metaDescription: 'Convert client bank statement PDFs into clean Excel or CSV in 15 seconds. Built for freelance bookkeepers and small bookkeeping practices juggling multiple clients. Free 50 pages/month.',
    keywords: [
      'bank statement tools for bookkeepers', 'bank statement converter for bookkeepers',
      'bookkeeper bank statement software', 'bank statement pdf to excel for bookkeeping',
      'freelance bookkeeper bank statement tool', 'bank reconciliation tool for bookkeepers',
    ],
    hero: {
      kicker: 'BUILT FOR BOOKKEEPERS',
      h1Prefix: 'Every client\'s statement,',
      h1Highlight: 'ready for your books in 15 seconds',
      h1Suffix: '.',
      subhead: 'Juggling a dozen clients means a dozen different bank formats to type up every month. BankXL converts any bank statement PDF into clean Excel or CSV instantly, so bookkeeping time goes into categorizing and reconciling, not retyping.',
    },
    proofPoints: ['Built for freelance & small-practice bookkeepers', '500+ banks supported', 'Free 50 pages/month'],
    painPoints: [
      'Stop retyping each client\'s statement into your bookkeeping software by hand',
      'End the monthly scramble across 10+ clients with 10+ different bank formats',
      'Skip manually splitting debit/credit columns from generic PDF exports',
      'Stop losing billable hours to data entry instead of actual bookkeeping',
    ],
    workflows: [
      { title: 'Monthly client close',
        before: 'Download each client\'s statement, type it into Excel or your accounting software, then start categorizing.',
        after: 'Upload the PDF → get a formatted Excel or CSV → import straight into QuickBooks, Zoho Books, or your ledger.' },
      { title: 'Multi-client month-end',
        before: 'Process 10-15 clients one at a time, each taking 20-30 minutes of manual entry.',
        after: 'Bulk upload every client\'s statement in one batch — conversions run in parallel while you work on something else.' },
      { title: 'Categorization and reconciliation',
        before: 'Manually read every transaction description to decide which ledger account it belongs to.',
        after: 'Get a clean Excel with amount, date, and narration already separated — plug straight into your categorization workflow.' },
      { title: 'New client onboarding',
        before: 'A new client hands over a year of statements; days go into typing before you can even start their books.',
        after: 'Convert the whole year in one batch and start reconciling from day one.' },
    ],
    features: [
      { title: 'CSV export for accounting software', big: true,
        desc: 'Export as CSV formatted for direct import into QuickBooks, Zoho Books, Xero, or Tally — skip re-keying transactions into your ledger entirely.' },
      { title: 'Bulk conversion for multiple clients', big: true,
        desc: 'Upload up to 50 statements in one batch on the Firm plan — ideal for a bookkeeping practice handling many small clients every month.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Scanned statements too',
        desc: 'Older passbook scans or faxed statements some clients still send are read at near-perfect accuracy.' },
      { title: 'Clean debit/credit separation',
        desc: 'Every transaction splits into debit and credit columns automatically, ready for categorization without manual sorting.' },
      { title: 'Client-safe by design',
        desc: 'Files processed in memory, deleted after conversion. Nothing shared with third parties — important when you\'re trusted with several clients\' finances at once.' },
    ],
    testimonial: {
      text: 'I bookkeep for 14 small businesses. What used to eat my entire first week of the month now takes an afternoon.',
      name: 'Neha Kapoor',
      role: 'Freelance Bookkeeper, Ahmedabad',
    },
    faqs: [
      { q: 'Can I import the output directly into QuickBooks or Zoho Books?',
        a: 'Yes — export as CSV, formatted with clean date/description/debit/credit columns that most accounting software accepts directly on import.' },
      { q: 'Is there a plan for handling many small clients?',
        a: 'Yes. The Firm plan supports bulk upload of up to 50 statements per batch and 5 team seats, priced for a small bookkeeping practice\'s volume.' },
      { q: 'Does it handle different bank formats consistently?',
        a: 'Yes — every bank\'s statement converts into the same column layout (date, description, debit, credit, balance, reference), so your workflow stays the same regardless of which bank a client uses.' },
      { q: 'What about clients who send scanned statements?',
        a: 'Scanned and image-based PDFs are supported at 95%+ accuracy, so you don\'t need to ask clients to re-send a "proper" digital copy.' },
      { q: 'Is client financial data kept private?',
        a: 'Yes. Files are processed in memory and deleted immediately after conversion. Nothing is stored long-term or used to train AI models.' },
      { q: 'Can I try it before committing to a paid plan?',
        a: 'Yes — 50 free pages every month, no credit card. Convert a couple of real client statements to check accuracy first.' },
    ],
  },

  // ─── CA Firms ───────────────────────────────────────────────────────────────
  'ca-firms': {
    slug: 'ca-firms',
    persona: 'CA Firms',
    personaShort: 'CA Firms',
    primaryKeyword: 'automated bank statement processing for ca firms',
    metaTitle: 'Bank Statement Processing for CA Firms',
    metaDescription: 'Automate bank statement processing across your whole CA firm. Bulk upload, team seats, and white-label Excel output. Built for firms handling 100+ client statements every month.',
    keywords: [
      'automated bank statement processing for ca firms', 'bank statement software for ca firms',
      'ca firm bank statement automation', 'bulk bank statement converter for firms',
      'bank statement processing tool for accounting firms', 'ca practice management bank statements',
    ],
    hero: {
      kicker: 'BUILT FOR CA FIRMS',
      h1Prefix: 'One tool, your whole firm,',
      h1Highlight: 'every client\'s bank statements',
      h1Suffix: '.',
      subhead: 'A mid-sized CA firm handles hundreds of client statements every month across partners, articles, and staff. BankXL gives your whole team one shared, bulk-capable converter — with your firm\'s name on every output.',
    },
    proofPoints: ['Built for multi-person CA practices', '5 team seats on Firm plan', '500+ banks supported'],
    painPoints: [
      'Stop each team member re-learning bank statement formatting from scratch',
      'End the inconsistency between how different articles/staff format client Excel sheets',
      'Skip manual data entry eating into billable audit and advisory hours firm-wide',
      'Stop losing client trust to typos from manual statement transcription',
    ],
    workflows: [
      { title: 'Firm-wide month-end processing',
        before: 'Every associate manually types up their assigned clients\' statements in whatever format they\'re used to.',
        after: 'The whole team uses one shared BankXL account — every output looks the same, with the firm\'s name and branding.' },
      { title: 'Onboarding a new client',
        before: 'A partner hands a new client\'s year of statements to an article, who spends days typing before real work begins.',
        after: 'Bulk upload the full year in one batch — the team starts reviewing structured data on day one.' },
      { title: 'Audit season capacity crunch',
        before: 'Every senior and article is buried in manual data entry across 50+ clients during peak season.',
        after: 'Bulk conversion processes dozens of statements in parallel, freeing the team to focus on actual audit procedures.' },
      { title: 'Consistent client deliverables',
        before: 'Different staff produce differently formatted Excel sheets for the same type of engagement.',
        after: 'Every conversion uses the same white-labeled template — consistent quality regardless of who ran it.' },
    ],
    features: [
      { title: 'White-label Excel with your firm\'s branding', big: true,
        desc: 'The Firm plan puts your firm\'s name in the Excel summary sheet — client-facing deliverables look like your firm\'s work product, not a third-party tool\'s.' },
      { title: '5 team seats, shared usage', big: true,
        desc: 'One subscription covers your whole team — partners, seniors, and articles all convert from the same account with shared history and usage.' },
      { title: 'Bulk upload up to 50 statements at once',
        desc: 'Process a batch of client statements in parallel — ideal for month-end, quarterly, or audit-season crunch periods.' },
      { title: 'Every Indian bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Tally XML export firm-wide',
        desc: 'Every team member can export Tally-ready XML directly — no plugin, no TDL, using Tally\'s built-in Ctrl+I import.' },
      { title: 'Client-safe by design',
        desc: 'Files processed in memory, deleted after conversion. Zero data retention across every seat on the account.' },
    ],
    testimonial: {
      text: 'We\'re a 12-person practice. Getting everyone off manual data entry and onto one shared tool cut our month-end close time by more than half.',
      name: 'Amit Verma',
      role: 'Partner, CA Firm, Pune',
    },
    faqs: [
      { q: 'How many people can use one Firm plan subscription?',
        a: 'The Firm plan includes 5 team seats. Additional seats can be added — email support@banlxlai.com for firm-specific pricing on larger teams.' },
      { q: 'Can output carry our firm\'s name instead of BankXL\'s?',
        a: 'Yes. Firm plan subscribers can set a custom brand name that appears in the Excel summary sheet on every conversion.' },
      { q: 'Can multiple team members work on different clients at the same time?',
        a: 'Yes — each seat can convert independently, and bulk upload lets one person queue up to 50 statements in a single batch.' },
      { q: 'Does everyone see the same conversion history?',
        a: 'Yes, usage and history are shared across the firm account so partners have visibility into what\'s been processed.' },
      { q: 'Is our clients\' financial data safe across the whole team?',
        a: 'Yes. Files are processed in memory and deleted immediately after conversion, regardless of which seat performs the conversion — zero long-term retention firm-wide.' },
      { q: 'Can we try it before committing the whole firm?',
        a: 'Yes — start on the free plan (50 pages/month) to test with a couple of real client statements, then upgrade to Firm when ready to onboard the team.' },
    ],
  },

  // ─── Finance Teams ──────────────────────────────────────────────────────────
  'finance-teams': {
    slug: 'finance-teams',
    persona: 'Finance Teams',
    personaShort: 'Finance Teams',
    primaryKeyword: 'finance team bank statement tool',
    metaTitle: 'Bank Statement Converter for Finance Teams',
    metaDescription: 'Convert bank statement PDFs into Excel, CSV or JSON for cash flow tracking, reconciliation, and reporting. Built for in-house finance and accounts teams. Free 50 pages/month.',
    keywords: [
      'finance team bank statement tool', 'bank statement converter for finance teams',
      'in-house finance bank statement processing', 'cash flow tracking bank statement tool',
      'corporate bank statement to excel', 'finance department bank reconciliation tool',
    ],
    hero: {
      kicker: 'BUILT FOR FINANCE TEAMS',
      h1Prefix: 'Cash flow visibility',
      h1Highlight: 'without the manual data entry',
      h1Suffix: '.',
      subhead: 'Tracking cash position across multiple company bank accounts means reading statements every week. BankXL converts any bank PDF into structured Excel, CSV, or JSON in 15 seconds — so your team spends time on analysis, not transcription.',
    },
    proofPoints: ['Used by in-house finance & accounts teams', '500+ banks supported', 'API access on Firm plan'],
    painPoints: [
      'Stop manually re-typing statements from every company bank account each week',
      'End the delay between "statement arrives" and "cash position is updated"',
      'Skip building the same Excel formatting from scratch every reporting cycle',
      'Stop losing finance-team hours to data entry instead of forecasting and analysis',
    ],
    workflows: [
      { title: 'Weekly cash position update',
        before: 'Download statements from each company bank account, manually type transactions into a cash flow tracker.',
        after: 'Upload each account\'s statement → get structured Excel or JSON → feed straight into your cash flow dashboard.' },
      { title: 'Multi-account reconciliation',
        before: 'Each of the company\'s 3-5 bank accounts needs separate manual entry before consolidated reconciliation.',
        after: 'Bulk upload all accounts — each converts into the same column layout for consolidated review.' },
      { title: 'Month-end close reporting',
        before: 'Finance team manually keys in bank transactions to close the books and prepare management reports.',
        after: 'Convert statements to Excel or CSV and import directly into your ERP or accounting system for close.' },
      { title: 'API-driven automation',
        before: 'A recurring manual task every reporting cycle, with no way to automate it.',
        after: 'Use the BankXL API (Firm plan) to programmatically convert statements as part of your existing finance automation pipeline.' },
    ],
    features: [
      { title: 'REST API for automation', big: true,
        desc: 'Firm plan includes API access — integrate bank statement conversion directly into your existing finance systems and automation pipelines instead of manual uploads.' },
      { title: 'JSON export for internal systems', big: true,
        desc: 'Export structured JSON that plugs directly into internal dashboards, cash flow trackers, or data warehouses.' },
      { title: 'Multi-account bulk processing',
        desc: 'Upload statements from every company bank account in one batch — up to 50 files on the Firm plan.' },
      { title: 'Every Indian and major international bank supported',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak + 90 more Indian banks, plus Chase, BoA, Wells Fargo, HSBC and other global banks.' },
      { title: 'Clean debit/credit separation',
        desc: 'Every transaction splits automatically into debit and credit columns, ready for cash flow categorization.' },
      { title: 'Enterprise-grade data handling',
        desc: 'Files processed in memory, deleted after conversion. No long-term retention, no AI training on your company\'s financial data.' },
    ],
    testimonial: {
      text: 'We track cash across five accounts. Automating the statement-to-spreadsheet step alone saved our team a full day every week.',
      name: 'Priya Sharma',
      role: 'Senior Accountant, Mumbai',
    },
    faqs: [
      { q: 'Is there an API for integrating with our internal systems?',
        a: 'Yes — the Firm plan includes REST API access so you can trigger conversions programmatically as part of your existing finance automation instead of manual uploads.' },
      { q: 'Can we process multiple company bank accounts at once?',
        a: 'Yes. Bulk upload supports up to 50 statements per batch on the Firm plan, each normalized to the same structure for consolidated cash flow analysis.' },
      { q: 'Does it support international banks if we have foreign accounts?',
        a: 'Yes — alongside 500+ Indian banks, BankXL supports major international banks including Chase, Bank of America, Wells Fargo, HSBC, and DBS.' },
      { q: 'What output format is best for feeding into our dashboards?',
        a: 'JSON is typically easiest for internal systems and dashboards. Excel and CSV are also available for manual review or spreadsheet-based workflows.' },
      { q: 'How is our company\'s financial data protected?',
        a: 'Files are processed in memory and deleted immediately after conversion. No long-term storage, and data is never used to train AI models.' },
      { q: 'Can we evaluate it before rolling out to the finance team?',
        a: 'Yes — the free plan includes 50 pages every month, no credit card required, so you can test accuracy on real statements first.' },
    ],
  },

  // ─── Small Businesses ───────────────────────────────────────────────────────
  'small-businesses': {
    slug: 'small-businesses',
    persona: 'Small Businesses',
    personaShort: 'Small Businesses',
    primaryKeyword: 'small business bank statement to excel',
    metaTitle: 'Bank Statement to Excel Converter for Small Businesses',
    metaDescription: 'Convert your business bank statement PDF to Excel or CSV in 15 seconds. Track expenses, prepare for your accountant, or do your own bookkeeping — no software to install, free to start.',
    keywords: [
      'small business bank statement to excel', 'bank statement converter for small business',
      'business bank statement pdf to excel', 'small business expense tracking bank statement',
      'bank statement to excel for business owners', 'convert business bank statement free',
    ],
    hero: {
      kicker: 'BUILT FOR SMALL BUSINESS OWNERS',
      h1Prefix: 'Your business bank statement,',
      h1Highlight: 'in Excel in 15 seconds',
      h1Suffix: '.',
      subhead: 'Whether you\'re tracking expenses yourself or getting statements ready to hand your accountant, BankXL converts any business bank statement PDF into clean Excel or CSV instantly — no software to install, no manual retyping.',
    },
    proofPoints: ['No accounting background needed', '500+ banks supported', 'Free 50 pages/month'],
    painPoints: [
      'Stop manually typing out every transaction to track business expenses',
      'End the back-and-forth with your accountant over "can you send it as Excel?"',
      'Skip fighting with generic PDF tools that jumble debit and credit into one column',
      'Stop losing time on bookkeeping instead of running your business',
    ],
    workflows: [
      { title: 'Monthly expense tracking',
        before: 'Manually type out every transaction from your current account statement into a spreadsheet to track spending.',
        after: 'Upload the PDF, get a categorized Excel with debit/credit already separated, and see where the money went instantly.' },
      { title: 'Preparing for your accountant',
        before: 'Your accountant asks for statements in Excel; you either type it up yourself or pay them to do it.',
        after: 'Convert to Excel or CSV yourself in 15 seconds and send a clean file your accountant can work with immediately.' },
      { title: 'Simple DIY bookkeeping',
        before: 'Running your own books means manually entering every bank transaction into a ledger or spreadsheet.',
        after: 'Convert statements monthly and paste the structured data straight into your bookkeeping spreadsheet or software.' },
      { title: 'Loan or credit application prep',
        before: 'A lender asks for 6-12 months of statements in a readable format; you scramble to compile them.',
        after: 'Convert each month\'s statement to Excel or CSV and submit clean, organized financial data.' },
    ],
    features: [
      { title: 'No software or signup friction', big: true,
        desc: 'Just upload your PDF and download the result — no accounting background or software installation needed. 50 pages free every month.' },
      { title: 'Clean debit/credit separation', big: true,
        desc: 'Every transaction splits automatically into debit and credit columns with a running balance, so you can see cash flow at a glance.' },
      { title: 'Works with every Indian bank',
        desc: 'SBI, HDFC, ICICI, Axis, Kotak, PNB, BoB, Canara, IDFC, IndusInd, Yes, Federal, RBL, IDBI, AU SFB + 90 more.' },
      { title: 'Excel, CSV, or JSON — your choice',
        desc: 'Download in whichever format works for you or your accountant — Excel for review, CSV for spreadsheet tools, JSON for developers.' },
      { title: 'Scanned statements supported',
        desc: 'Even an older passbook-style scan or photo of a statement converts at 95%+ accuracy.' },
      { title: 'Your data stays private',
        desc: 'Files are processed in memory and deleted immediately after conversion — nothing is stored or shared.' },
    ],
    testimonial: {
      text: 'I run a small retail shop and used to dread sending my accountant a stack of PDFs. Now I convert them myself in under a minute each.',
      name: 'Amit Verma',
      role: 'Small Business Owner, Pune',
    },
    faqs: [
      { q: 'Do I need accounting knowledge to use this?',
        a: 'No. Just upload your bank statement PDF and download the converted Excel or CSV — no accounting background required.' },
      { q: 'Can I send the output straight to my accountant?',
        a: 'Yes — the Excel format includes a clean transaction table and summary sheet that most accountants can work with directly.' },
      { q: 'Is it really free?',
        a: 'Yes, up to 50 pages every month with no credit card required. That typically covers several months of a small business current account statement.' },
      { q: 'Does it work with my specific bank?',
        a: 'Almost certainly — 500+ banks are supported including all major Indian banks. If yours isn\'t recognized, email a sample to support@banlxlai.com and we\'ll add it.' },
      { q: 'What if my statement is a scanned copy or photo?',
        a: 'Scanned and image-based PDFs are supported at 95%+ accuracy, so an older-style passbook scan still converts cleanly.' },
      { q: 'Is my business\'s financial data kept private?',
        a: 'Yes. Files are processed in memory and deleted immediately after conversion — nothing is stored long-term or shared with anyone.' },
    ],
  },
}

export const ALL_PERSONA_SLUGS = Object.keys(PERSONA_PAGES)
